#!/bin/sh

bspc config border_width   2
bspc config window_gap     15

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

# colors
bspc config normal_border_color          "#2b3032"
bspc config focused_border_color         "#2b3032"
bspc config active_border_color          "#2b3032"
bspc config presel_border_color          "#dfdfdf"
bspc config focused_locked_border_color  "#2b3032"
bspc config active_locked_border_color   "#2b3032"
bspc config normal_locked_border_color   "#2b3032"
bspc config focused_sticky_border_color  "#2b3032"
bspc config active_sticky_border_color   "#2b3032"
bspc config normal_sticky_border_color   "#2b3032"
bspc config focused_private_border_color "#2b3032"
bspc config active_private_border_color  "#2b3032"
bspc config normal_private_border_color  "#2b3032"
bspc config urgent_border_color          "#2b3032"

for monitor in $(bspc query -M); do
  if [ "$monitor" == "eDP1" ]; then
    bspc monitor $monitor -n B
    bspc monitor B -d '' '' ''
  elif [ -n "$monitor" ]; then
    bspc monitor $monitor -n T
    bspc monitor T -d ''
  fi
done

# autostart
feh --bg-scale $HOME/Pictures/ship.jpg
compton -cCGf --backend glx --paint-on-overlay --vsync opengl-swc &
$HOME/.config/bspwm/panel &
