#!/bin/sh

bspc config border_width   2
bspc config window_gap     15

bspc config split_ratio           0.56
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

# colors
bspc config normal_border_color          "#2b3032"
bspc config focused_border_color         "#667777"
bspc config active_border_color          "#2b3032"
bspc config presel_border_color          "#dfdfdf"
bspc config focused_locked_border_color  "#2b3032"
bspc config active_locked_border_color   "#2b3032"
bspc config normal_locked_border_color   "#2b3032"
bspc config focused_sticky_border_color  "#2b3032"
bspc config active_sticky_border_color   "#2b3032"
bspc config normal_sticky_border_color   "#2b3032"
bspc config focused_private_border_color "#2b3032"
bspc config active_private_border_color  "#2b3032"
bspc config normal_private_border_color  "#2b3032"
bspc config urgent_border_color          "#2b3032"

num_monitors=$(bspc query -M | wc -l)
primary_monitor=$(xrandr | grep -E "eDP" | awk '{print $1}')
#secondary_flags="--above $primary_monitor"
secondary_flags="--same-as $primary_monitor"

if [[ $num_monitors -eq 1 ]]; then
  bspc monitor $primary_monitor -n P
  bspc monitor P -d '' '' ''
else
  secondary_monitor=$(bspc query -M | grep -v $primary_monitor)
  xrandr --output $primary_monitor --primary \
         --output $secondary_monitor $secondary_flags \
         --output VIRTUAL1 --off

  if echo $secondary_flags | grep -q "same-as"; then
    bspc monitor $primary_monitor -n P
    bspc monitor $secondary_monitor -n _
    bspc monitor P -d '' '' ''
    bspc monitor _ -d _
  else
    bspc monitor $primary_monitor -n B
    bspc monitor $secondary_monitor -n T
    bspc monitor B -d '' ''
    bspc monitor T -d ''
    bspc monitor T -s B
  fi
fi

# window rules
bspc rule -a zoom        state=floating
bspc rule -a Gimp        state=floating
bspc rule -a FromScratch state=floating
#bspc rule -a Vmware state=floating

# autostart
xmodmap -e "add mod3 = Menu"
feh --bg-scale $HOME/Pictures/ship.jpg
compton -cCGf --backend glx --paint-on-overlay --vsync opengl-swc &
$HOME/.config/bspwm/panel &
