#!/bin/sh

bspc config border_width   2
bspc config window_gap     25

bspc config top_padding    5
bspc config right_padding  0
bspc config bottom_padding 5
bspc config left_padding   0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config focus_follows_pointer true

# colors
bspc config normal_border_color          "#2b3032"
bspc config focused_border_color         "#2b3032"
bspc config active_border_color          "#2b3032"
bspc config presel_border_color          "#dfdfdf"
bspc config focused_locked_border_color  "#2b3032"
bspc config active_locked_border_color   "#2b3032"
bspc config normal_locked_border_color   "#2b3032"
bspc config focused_sticky_border_color  "#2b3032"
bspc config active_sticky_border_color   "#2b3032"
bspc config normal_sticky_border_color   "#2b3032"
bspc config focused_private_border_color "#2b3032"
bspc config active_private_border_color  "#2b3032"
bspc config normal_private_border_color  "#2b3032"
bspc config urgent_border_color          "#2b3032"

#bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf268') $(echo -e '\uf120') $(echo -e '\uf001') $(echo -e '\uf181') $(echo -e '\uf126') $(echo -e '\uf008') $(echo -e '\uf1b6') $(echo -e '\uf085') $(echo -e '\uf1fc')

# autostart
$HOME/.fehbg
compton -cCGf --backend glx --paint-on-overlay --vsync opengl-swc &
