#!/bin/sh

network() {
  while true; do
    read lo int1 int2 etc <<< `ip link | sed -n 's/^[0-9]: \(.*\):.*$/\1/p'`

    if iwconfig $int1 >/dev/null 2>&1; then
        wlan0=$int1
        eth0=$int2
    else
        wlan0=$int2
        eth0=$int1
    fi

    int=""
    ip link show $eth0 | grep 'state UP' >/dev/null && int=$eth0 || int=$wlan0

    if [[ "$int" != "$eth0" && -d /proc/sys/net/ipv4/conf/tun0 ]]; then
      echo -e 'N\uf00c vpn'
    else
      ping -W 1 -c 1 8.8.8.8 >/dev/null 2>&1 &&
        echo -e 'N\uf00c ' $int || echo -e 'N\uf00d ' $wlan0
    fi

    sleep 1.0
  done
}

#network
