#!/bin/sh

network() {
  while true; do
    read int1 int2 int3 etc <<< $(ip link | grep -E "(enp|wlp)" | sed -n 's/.*: \(.*\):.*$/\1/p' | tr '\n' ' ')

    if [[ -d /proc/sys/net/ipv4/conf/tun0 ]]; then
      echo "N vpn"
    else
      if iwconfig $int1 >/dev/null 2>&1; then
        wlan0=$int1
        eth0=$int2
        eth1=$int3
      elif iwconfig $int2 >/dev/null 2>&1; then
        echo "here $int2 here"
        eth0=$int1
        wlan0=$int2
        eth1=$int3
      elif iwconfig $int3 >/dev/null 2>&1; then
        eth0=$int1
        eth1=$int2
        wlan0=$int3
      fi

      interface=""
      ip link show $eth0 | grep 'state UP' >/dev/null && interface=$eth0
      ip link show $eth1 | grep 'state UP' >/dev/null && interface=$eth1
      [[ -z "$interface" ]] && interface=$wlan0

      if [[ "$interface" == "$wlan0" ]]; then
        ping -W 1 -c 1 8.8.8.8 >/dev/null 2>&1 &&
          echo "N $interface" || echo "N $wlan0"
      else
        ping -W 1 -c 1 8.8.8.8 >/dev/null 2>&1 &&
          echo "N $interface" || echo "N $wlan0"
      fi
    fi

    sleep 2.5
  done
}

#network
