#!/bin/sh

[[ $(pgrep -cx panel) -gt 1 ]] && printf "%s\n" "The panel is already running!" >&2 && exit 1

. $HOME/.config/bspwm/color
. $HOME/.config/bspwm/network
. $HOME/.config/bspwm/clock
. $HOME/.config/bspwm/power
. $HOME/.config/bspwm/mixer

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT
pipe=$(mktemp -u)
mkfifo $pipe

bspc config top_padding 25

{ bspc subscribe report > $pipe; } &
{ xtitle -sf 'T%s'      > $pipe; } &
{ network               > $pipe; } &
{ clock                 > $pipe; } &
{ power                 > $pipe; } &
{ mixer                 > $pipe; } &

bspwm_data=""
title_data=""
power_data=""
clock_data=""
mixer_data=""
network_data=""
while read line; do
  num_monitors=$(bspc query -M | wc -l)
  case $line in
    T*)
      title_data="%{F$COLOR_FOREGROUND}%{B$COLOR_BACKGROUND} ${line#?} %{B-}%{F-}"
      ;;
    N*)
      network_data="%{F$COLOR_FOREGROUND}%{B$COLOR_BACKGROUND} ${line#?} %{B-}%{F-}"
      ;;
    C*)
      clock_data="%{F$COLOR_FOREGROUND}%{B$COLOR_BACKGROUND} ${line#?} %{B-}%{F-}"
      ;;
    P*)
      power_data="%{F$COLOR_FOREGROUND}%{B$COLOR_BACKGROUND} ${line#?} %{B-}%{F-}"
      ;;
    V*)
      mixer_data="%{F$COLOR_FOREGROUND}%{B$COLOR_BACKGROUND} ${line#?} %{B-}%{F-}"
      ;;
    W*)
      IFS=':'
      bspwm_data=""

      set -- ${line#?}
      while [ $# -gt 0 ]; do
        item=$1
        name=${item#?}
        case $item in
          M*)
            # active monitor
            if [ $num_monitors -gt 1 ] ; then
              bspwm_data="$bspwm_data %{F$COLOR_FOREGROUND}%{B$COLOR_BACKGROUND}  ${name}  %{B-}%{F-}  "
            fi
            ;;
          m*)
            # inactive monitor
            if [ $num_monitors -gt 1 ] ; then
              bspwm_data="$bspwm_data %{F$COLOR_FOREGROUND}%{B$COLOR_BACKGROUND}  ${name}  %{B-}%{F-}  "
            fi
            ;;
          O*)
            # focused occupied desktop
            bspwm_data="${bspwm_data}%{F$COLOR_FOCUSED_FOREGROUND}%{B$COLOR_FOCUSED_BACKGROUND}%{U$COLOR_FOREGROUND}%{+u}  ${name}  %{-u}%{B-}%{F-}"
            ;;
          F*)
            # focused free desktop
            bspwm_data="${bspwm_data}%{F$COLOR_FOCUSED_FOREGROUND}%{B$COLOR_FOCUSED_BACKGROUND}%{U$COLOR_FOREGROUND}%{+u}  ${name}  %{-u}%{B-}%{F-}"
            ;;
          U*)
            # focused urgent desktop
            bspwm_data="${bspwm_data}%{F$COLOR_URGENT_FOREGROUND}%{B$COLOR_URGENT_BACKGROUND}%{U$COLOR_URGENT_FOREGROUND}%{+u}  ${name}  %{-u}%{B-}%{F-}"
            ;;
          o*)
            # occupied desktop
            bspwm_data="${bspwm_data}%{F$COLOR_FOREGROUND}%{B$COLOR_BACKGROUND}  ${name}  %{B-}%{F-}"
            ;;
          f*)
            # free desktop
            bspwm_data="${bspwm_data}%{F$COLOR_EMPTY_FOREGROUND}%{B$COLOR_EMPTY_BACKGROUND}  ${name}  %{B-}%{F-}"
            ;;
          u*)
            # urgent desktop
            bspwm_data="${bspwm_data}%{F$COLOR_URGENT_FOREGROUND}%{B$COLOR_URGENT_BACKGROUND}%{U$COLOR_URGENT_FOREGROUND}%{+u}  ${name}  %{-u}%{B-}%{F-}"
            ;;
        esac
        shift
      done
      ;;
  esac

  echo "%{l} ${bspwm_data}%{c}${title_data}%{r}${mixer_data} ${network_data} ${power_data} ${clock_data} "
done < $pipe | lemonbar -g x25 -f "FontAwesome:size=10" -f "Hack:size=10" -F $COLOR_FOREGROUND -B $COLOR_BACKGROUND

