#!/bin/bash

power() {
  while true; do
    icon=''
    level=$(acpi -b | grep -o '[[:digit:]]\+%' | sed 's/%//')
    if [[ $(cat /sys/class/power_supply/ADP1/online) != 1 ]]; then
      icon=''
      [[ $level -gt 10 ]] && icon=''
      [[ $level -gt 30 ]] && icon=''
      [[ $level -gt 60 ]] && icon=''
      [[ $level -gt 80 ]] && icon=''
    fi

    echo -e 'P' $icon "$level%"
    sleep 20.0
  done
}
